$(document).ready(function() {
    $('#btnfix').click(function() {
    var textarea=$('#Unicode'); 

textarea.val(textarea.val().replace(/ର୍ୟ୍ୟ/g,"ର୍ଯ୍ୟ"));
textarea.val(textarea.val().replace(/ତ୍ଵ/g,"ତ୍ବ")); 
textarea.val(textarea.val().replace(/ସ୍ଵ/g,"ସ୍ବ"));
textarea.val(textarea.val().replace(/ଵ/g,"ବ"));
textarea.val(textarea.val().replace(/ଡ଼/g,"ଡ଼"));
textarea.val(textarea.val().replace(/ ଜ୍ଝ/g,"।"));
textarea.val(textarea.val().replace(/,  /g,", "));
textarea.val(textarea.val().replace(/ ।/g,"।"));
textarea.val(textarea.val().replace(/ଅଂକ/g,"ଅଙ୍କ"));
textarea.val(textarea.val().replace(/ବଂଟନ/g,"ବଣ୍ଟନ"));
textarea.val(textarea.val().replace(/କଂଚି/g,"କଞ୍ଚି"));
textarea.val(textarea.val().replace(/ଅଂଚ/g,"ଅଞ୍ଚ"));
textarea.val(textarea.val().replace(/ସଂଜ/g,"ସଞ୍ଜ"));
textarea.val(textarea.val().replace(/ଆଂଚ/g,"ଆଞ୍ଚ"));
textarea.val(textarea.val().replace(/ଯୋଗୁ/g,"ଯୋଗୁଁ"));
textarea.val(textarea.val().replace(/ଊର୍ଦ୍ଧ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଊଦ୍ଧ୍ବ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଊଦ୍ଧ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଊଧ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଊର୍ଧ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଊଧ୍ବ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଊର୍ଧ୍ବ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଉର୍ଦ୍ଧ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଉଦ୍ଧ୍ବ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଉଧ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଉର୍ଧ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଉଧ୍ବ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଉର୍ଧ୍ବ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଊର୍ଦ୍ଧ୍ବଧ୍ବ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଗ୍ରିଲ/g,"ଗ୍ରିଲ୍‌"));
textarea.val(textarea.val().replace(/ପ୍ରତିଶୃତି/g,"ପ୍ରତିଶ୍ରୁତି"));
textarea.val(textarea.val().replace(/ସ୍ବାଧିନତା/g,"ସ୍ବାଧୀନତା"));
textarea.val(textarea.val().replace(/ଶଯା/g,"ଶଯ୍ୟା"));
textarea.val(textarea.val().replace(/ଶର୍ଯ୍ୟା/g,"ଶଯ୍ୟା"));
textarea.val(textarea.val().replace(/ଜନେକ/g,"ଜନୈକ"));
textarea.val(textarea.val().replace(/ବଂଧ/g,"ବନ୍ଧ"));
textarea.val(textarea.val().replace(/କଂଧ/g,"କନ୍ଧ"));
textarea.val(textarea.val().replace(/ରଂଧ/g,"ରନ୍ଧ"));
textarea.val(textarea.val().replace(/ଊର୍ଦ୍ଧ୍ବ୍ବ/g,"ଊର୍ଦ୍ଧ୍ବ"));
textarea.val(textarea.val().replace(/ଜୈନିକ/g,"ଜନୈକ"));
textarea.val(textarea.val().replace(/ଜୈନେକ/g,"ଜନୈକ"));
textarea.val(textarea.val().replace(/ସ୍ବଚ/g,"ସ୍ବଚ୍ଛ"));
textarea.val(textarea.val().replace(/ସ୍ବଛ/g,"ସ୍ବଚ୍ଛ"));
textarea.val(textarea.val().replace(/ଚ୍ଛ୍ଛ/g,"ଚ୍ଛ"));
textarea.val(textarea.val().replace(/ଚ୍ଛ୍ଚ/g,"ଚ୍ଛ"));
textarea.val(textarea.val().replace(/ଗଡ/g,"ଗଡ଼"));
textarea.val(textarea.val().replace(/ଗଡି/g,"ଗଡ଼ି"));
textarea.val(textarea.val().replace(/ପଡି/g,"ପଡ଼ି"));
textarea.val(textarea.val().replace(/ଏନ.ଏ.ସି./g,"ଏନ୍‌ଏସି"));
textarea.val(textarea.val().replace(/ଏନ୍‌.ଏ.ସି./g,"ଏନ୍‌ଏସି"));
textarea.val(textarea.val().replace(/ଏନ୍‌.ସି.ସି./g,"ଏନ୍‌ସିସି"));
textarea.val(textarea.val().replace(/ଏନ୍‌.ଏ.ସି/g,"ଏନ୍‌ଏସି"));
textarea.val(textarea.val().replace(/ଏନ.ଏ.ସି/g,"ଏନ୍‌ଏସି"));
textarea.val(textarea.val().replace(/ବି.ଡି.ଓ/g,"ବିଡିଓ"));
textarea.val(textarea.val().replace(/ବିଛିନ୍ନ/g,"ବିଚ୍ଛିନ୍ନ"));
textarea.val(textarea.val().replace(/ପଂଚ/g,"ପଞ୍ଚ"));
textarea.val(textarea.val().replace(/ପଂଚା/g,"ପଞ୍ଚା"));
textarea.val(textarea.val().replace(/ଖୁଂଟ/g,"ଖୁଣ୍ଟ"));
textarea.val(textarea.val().replace(/ଅଂଟ/g,"ଅଣ୍ଟ"));
textarea.val(textarea.val().replace(/ଅଙ୍ଗନୱାଡ଼ି/g,"ଅଙ୍ଗନବାଡ଼ି"));
textarea.val(textarea.val().replace(/ଗଡ଼଼/g,"ଗଡ଼"));
        });
});
